advent/advent \
advent/advent.db \
ash/ash \
basic/basic \
bc/bc \
busyelks/busyelks \
cron/cron \
cron/crontab \
disk_utils/df \
disk_utils/fdisk \
disk_utils/fsck \
disk_utils/mkfat \
disk_utils/mkfs \
disk_utils/partype \
disk_utils/ramdisk \
elvis/elvis \
file_utils/cat \
file_utils/chgrp \
file_utils/chmod \
file_utils/chown \
file_utils/cmp \
file_utils/cp \
file_utils/dd \
file_utils/ln \
file_utils/ls \
file_utils/md5sum \
file_utils/mkdir \
file_utils/mkfifo \
file_utils/mknod \
file_utils/more \
file_utils/mv \
file_utils/rm \
file_utils/rmdir \
file_utils/split \
file_utils/sync \
file_utils/touch \
fsck_dos/fsck-dos \
inet/ftp/ftp \
inet/ftp/ftpd \
inet/httpd/httpd \
inet/httpd/sample_index.html \
inet/nettools/arp \
inet/nettools/netstat \
inet/nettools/nslookup \
inet/telnetd/telnetd \
inet/telnet/telnet \
inet/tinyirc/tinyirc \
inet/urlget/urlget \
ktcp/ktcp \
m4/m4 \
minix1/banner \
minix1/cksum \
minix1/cut \
minix1/decomp16 \
minix1/du \
minix1/fgrep \
minix1/grep \
minix1/proto \
minix1/sum \
minix1/uniq \
minix1/wc \
minix2/env \
minix2/lp \
minix2/man \
minix2/pwdauth \
minix2/remsync \
minix2/synctree \
minix2/tget \
minix3/cal \
minix3/diff \
minix3/file \
minix3/find \
minix3/head \
minix3/mail \
minix3/sed \
minix3/sort \
minix3/tail \
minix3/tee \
misc_utils/compress \
misc_utils/ed \
misc_utils/fdtest \
misc_utils/hd \
misc_utils/kilo \
misc_utils/mined \
misc_utils/miniterm \
misc_utils/od \
misc_utils/sleep \
misc_utils/tar \
misc_utils/time \
misc_utils/tty \
misc_utils/uudecode \
misc_utils/uuencode \
mtools/mcopy \
mtools/mdel \
mtools/mdir \
mtools/mkdfs \
mtools/mmd \
mtools/mrd \
mtools/mread \
mtools/mren \
mtools/mtype \
mtools/mwrite \
nano/nano-2.0.6/src/nano \
nano-X/bin/nxworld.map \
prems/pres/pres \
sash/sash \
screen/screen \
sh_utils/basename \
sh_utils/clear \
sh_utils/date \
sh_utils/dirname \
sh_utils/echo \
sh_utils/false \
sh_utils/logname \
sh_utils/mesg \
sh_utils/printenv \
sh_utils/pwd \
sh_utils/stty \
sh_utils/test \
sh_utils/tr \
sh_utils/true \
sh_utils/uname \
sh_utils/which \
sh_utils/whoami \
sh_utils/xargs \
sh_utils/yes \
sys_utils/chmem \
sys_utils/clock \
sys_utils/console \
sys_utils/getty \
sys_utils/init \
sys_utils/kill \
sys_utils/login \
sys_utils/makeboot \
sys_utils/man \
sys_utils/meminfo \
sys_utils/min_init \
sys_utils/mount \
sys_utils/mouse \
sys_utils/passwd \
sys_utils/poweroff \
sys_utils/ps \
sys_utils/reboot \
sys_utils/sercat \
sys_utils/shutdown \
sys_utils/umount \
sys_utils/unreal16 \
sys_utils/who \
test/libc/test_libc \
test/other/test_float \
tui/cons \
tui/fm \
tui/matrix \
tui/sl \
tui/ttyinfo \
: .FORCE
	@echo 'MAKE	$@'
	$(V)make -C $(dir $@) $(notdir $@)

nano-X/bin/nxclock \
nano-X/bin/nxdemo \
nano-X/bin/nxlandmine \
nano-X/bin/nxterm \
nano-X/bin/nxtest \
nano-X/bin/nxtetris \
nano-X/bin/nxworld \
: .FORCE
	make -C nano-X/ $(subst nano-X/,,$@) 

disk_utils/df \
disk_utils/mkfs \
disk_utils/mkfat \
file_utils/cp \
file_utils/rm \
inet/httpd/httpd \
inet/nettools/arp \
inet/nettools/netstat \
inet/telnet/telnet \
inet/urlget/urlget \
minix1/cksum \
minix1/du \
minix1/sum \
minix2/env \
minix2/lp \
minix3/cal \
minix3/file \
misc_utils/fdtest \
sh_utils/which \
sh_utils/mesg \
sys_utils/getty \
sys_utils/mount \
: lib/tiny_vfprintf.o

lib/tiny_vfprintf.o: lib/tiny_vfprintf.c
	$(V)make -C $(dir $@) $(notdir $@)

$(DESTDIR)/usr/bin/cgatext \
 :
	mkdir -p $(dir $@)
	cp $< $@

$(DESTDIR)/usr/bin/cgatext: cgatext/cgatext

cgatext/cgatext \
misc_utils/fdtest \
: ../elks/arch/i86/lib/lib86.a

../elks/arch/i86/lib/lib86.a: .FORCE
	make -C $(dir $@) $(notdir $@)

.FORCE: ;
